//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4963.
// 
#pragma warning disable 1591

namespace TaxDetails.gr.gsis.www1 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RgWsBasStoixNSoapHttp", Namespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenWsErrorRtBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RgWsBasStoixNRtBase))]
    public partial class RgWsBasStoixN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback rgWsBasStoixNOperationCompleted;
        
        private System.Threading.SendOrPostCallback rgWsBasStoixNVersionInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RgWsBasStoixN() {
            this.Url = global::TaxDetails.Properties.Settings.Default.TaxDetails_gr_gsis_www1_RgWsBasStoixN;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event rgWsBasStoixNCompletedEventHandler rgWsBasStoixNCompleted;
        
        /// <remarks/>
        public event rgWsBasStoixNVersionInfoCompletedEventHandler rgWsBasStoixNVersionInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/rgWsBasStoixN", RequestNamespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", ResponseNamespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void rgWsBasStoixN(string pAfm, ref RgWsBasStoixNRtUser pBasStoixNRec_out, ref decimal pCallSeqId_out, ref GenWsErrorRtUser pErrorRec_out) {
            object[] results = this.Invoke("rgWsBasStoixN", new object[] {
                        pAfm,
                        pBasStoixNRec_out,
                        pCallSeqId_out,
                        pErrorRec_out});
            pBasStoixNRec_out = ((RgWsBasStoixNRtUser)(results[0]));
            pCallSeqId_out = ((decimal)(results[1]));
            pErrorRec_out = ((GenWsErrorRtUser)(results[2]));
        }
        
        /// <remarks/>
        public void rgWsBasStoixNAsync(string pAfm, RgWsBasStoixNRtUser pBasStoixNRec_out, decimal pCallSeqId_out, GenWsErrorRtUser pErrorRec_out) {
            this.rgWsBasStoixNAsync(pAfm, pBasStoixNRec_out, pCallSeqId_out, pErrorRec_out, null);
        }
        
        /// <remarks/>
        public void rgWsBasStoixNAsync(string pAfm, RgWsBasStoixNRtUser pBasStoixNRec_out, decimal pCallSeqId_out, GenWsErrorRtUser pErrorRec_out, object userState) {
            if ((this.rgWsBasStoixNOperationCompleted == null)) {
                this.rgWsBasStoixNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrgWsBasStoixNOperationCompleted);
            }
            this.InvokeAsync("rgWsBasStoixN", new object[] {
                        pAfm,
                        pBasStoixNRec_out,
                        pCallSeqId_out,
                        pErrorRec_out}, this.rgWsBasStoixNOperationCompleted, userState);
        }
        
        private void OnrgWsBasStoixNOperationCompleted(object arg) {
            if ((this.rgWsBasStoixNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rgWsBasStoixNCompleted(this, new rgWsBasStoixNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/rgWsBasStoixNVersionInfo", RequestNamespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", ResponseNamespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public string rgWsBasStoixNVersionInfo() {
            object[] results = this.Invoke("rgWsBasStoixNVersionInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rgWsBasStoixNVersionInfoAsync() {
            this.rgWsBasStoixNVersionInfoAsync(null);
        }
        
        /// <remarks/>
        public void rgWsBasStoixNVersionInfoAsync(object userState) {
            if ((this.rgWsBasStoixNVersionInfoOperationCompleted == null)) {
                this.rgWsBasStoixNVersionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrgWsBasStoixNVersionInfoOperationCompleted);
            }
            this.InvokeAsync("rgWsBasStoixNVersionInfo", new object[0], this.rgWsBasStoixNVersionInfoOperationCompleted, userState);
        }
        
        private void OnrgWsBasStoixNVersionInfoOperationCompleted(object arg) {
            if ((this.rgWsBasStoixNVersionInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rgWsBasStoixNVersionInfoCompleted(this, new rgWsBasStoixNVersionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/types/")]
    public partial class RgWsBasStoixNRtUser : RgWsBasStoixNRtBase {
        
        private string actLongDescrField;
        
        private string postalZipCodeField;
        
        private System.Nullable<decimal> facActivityField;
        
        private System.Nullable<System.DateTime> registDateField;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private string doyDescrField;
        
        private string parDescriptionField;
        
        private string deactivationFlagField;
        
        private string postalAddressNoField;
        
        private string postalAddressField;
        
        private string doyField;
        
        private string firmPhoneField;
        
        private string onomasiaField;
        
        private string firmFaxField;
        
        private string afmField;
        
        private string commerTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string actLongDescr {
            get {
                return this.actLongDescrField;
            }
            set {
                this.actLongDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postalZipCode {
            get {
                return this.postalZipCodeField;
            }
            set {
                this.postalZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> facActivity {
            get {
                return this.facActivityField;
            }
            set {
                this.facActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> registDate {
            get {
                return this.registDateField;
            }
            set {
                this.registDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> stopDate {
            get {
                return this.stopDateField;
            }
            set {
                this.stopDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doyDescr {
            get {
                return this.doyDescrField;
            }
            set {
                this.doyDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string parDescription {
            get {
                return this.parDescriptionField;
            }
            set {
                this.parDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deactivationFlag {
            get {
                return this.deactivationFlagField;
            }
            set {
                this.deactivationFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postalAddressNo {
            get {
                return this.postalAddressNoField;
            }
            set {
                this.postalAddressNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doy {
            get {
                return this.doyField;
            }
            set {
                this.doyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string firmPhone {
            get {
                return this.firmPhoneField;
            }
            set {
                this.firmPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string onomasia {
            get {
                return this.onomasiaField;
            }
            set {
                this.onomasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string firmFax {
            get {
                return this.firmFaxField;
            }
            set {
                this.firmFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                this.afmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string commerTitle {
            get {
                return this.commerTitleField;
            }
            set {
                this.commerTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RgWsBasStoixNRtUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/types/")]
    public partial class RgWsBasStoixNRtBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenWsErrorRtUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/types/")]
    public partial class GenWsErrorRtBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gr/gsis/rgwsbasstoixn/RgWsBasStoixN.wsdl/types/")]
    public partial class GenWsErrorRtUser : GenWsErrorRtBase {
        
        private string errorDescrField;
        
        private string errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorDescr {
            get {
                return this.errorDescrField;
            }
            set {
                this.errorDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void rgWsBasStoixNCompletedEventHandler(object sender, rgWsBasStoixNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rgWsBasStoixNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rgWsBasStoixNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RgWsBasStoixNRtUser pBasStoixNRec_out {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RgWsBasStoixNRtUser)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public decimal pCallSeqId_out {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public GenWsErrorRtUser pErrorRec_out {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GenWsErrorRtUser)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void rgWsBasStoixNVersionInfoCompletedEventHandler(object sender, rgWsBasStoixNVersionInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rgWsBasStoixNVersionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rgWsBasStoixNVersionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591